# Binance Futures Configuration — Testnet Account
# Copy this to config.py and fill in your values

API_KEY = "YOUR_API_KEY_HERE"
API_SECRET = "YOUR_API_SECRET_HERE"

FUTURES_URL = "https://testnet.binancefuture.com"

STOP_LOSS_PCT = 2.5
TAKE_PROFIT_PCT = 5.0
RISK_PER_TRADE = 0.025
MAX_POSITIONS = 3
LEVERAGE = 20

COINS_WHITELIST = [
    "BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "XRPUSDT",
    "DOGEUSDT", "ADAUSDT", "AVAXUSDT", "DOTUSDT", "LINKUSDT",
    "MATICUSDT", "LTCUSDT", "ATOMUSDT", "UNIUSDT", "ETCUSDT",
    "SHIBUSDT", "PEPEUSDT", "FLOKIUSDT", "ARBUSDT", "OPUSDT",
]
COIN_UNIVERSE = "whitelist"
MIN_VOLUME_24H = 10_000_000

RSI_OVERSOLD = 30
RSI_OVERBOUGHT = 70
MOM_THRESHOLD = 0.15
VOL_RATIO_MIN = 1.5
CONF_ALERT = 7

USE_DYNAMIC_SL = True
STOP_LOSS_ATR_MULT = 2.0
STOP_LOSS_PCT_FALLBACK = 2.5

USE_EMA_FILTER = True
EMA_LENGTH = 20

USE_PARTIAL_TP = True
TP_1_RATIO = 2.0
TP_2_RATIO = 3.0

ENABLE_ALERTS = True
ALERT_ON_ENTRY = True
ALERT_ON_EXIT = True
ALERT_ON_SL = True
ALERT_ON_TP = True

DISCORD_WEBHOOK = "YOUR_WEBHOOK_URL_HERE"
DISCORD_BOT_TOKEN = "YOUR_BOT_TOKEN_HERE"
